= Handling errors

Whenever possible the library tries to return first encountered bottom most error.
But there are some optimistic matchers like:

* link:apidocs/org/jparsec/Api.html#many(org.jparsec.Matcher)[many()]
* link:apidocs/org/jparsec/Api.html#opt(org.jparsec.Matcher)[opt()]

that always succeed. This complicates the development but it is not impossible to get
these errors. About that in a second.

[source, java]
----
var identifier = seq(nonZeroDigit(), many(digit())).str();

var result = identifier.parse("01");

out.println(result.error());
----

----
expected non zero digit
----

Sometimes you may want to return more helpful, domain specific error messages.
For example instead of error on char level you would like to say that the literal is invalid.

[source, java]
----
var identifier = seq(nonZeroDigit(), many(digit())).str();
identifier = identifier.setErrorMessage("wrong literal");

var result = identifier.parse("01");

out.println(result.error());
----

----
wrong literal
----

You can do that with link:apidocs/org/jparsec/Matcher.html#setErrorMessage(java.lang.String)[setErrorMessage()] method on the matcher. It has
the tradeoff that the topmost customized message overrides all error messages on the bottom. So it
should be used sparingly and only for non-related rules.

There are various methods on the result to inspect the error further.

* link:apidocs/org/jparsec/containers/MatchResult.html#errorTrace()[errorTrace()]
* link:apidocs/org/jparsec/containers/MatchResult.html#errorPrettyPrint()[errorPrettyPrint()]
* link:apidocs/org/jparsec/containers/MatchResult.html#verboseErrors()[verboseErrors()]

*errorTrace()* allows to investige the whole "stack" from top to bottom when the matcher fails.

[source, java]
----
out.println(result.errorTrace());
----
----
Line: 0, Column: 0 => error in mapping
 +- Line: 0, Column: 0 => error in sequence
  +- Line: 0, Column: 0 => expected non zero digit
----

Unfortunately it won't print the stack for optimistic rules like
`many()` `opt()` and `sepBy()`. But errors are still logged and
you can view all the logs with *verboseErrors()*. Just take into
account that some errors are completely normal during the parsing.

[source, java]
----
var as = many(c('a')).str();

var result = as.parse("aab");
out.println(result.verboseErrors());
----

----
Line: 0, Column: 2 => expected 'a'
----

For obtaining compiler like messages with line number, column and content context
you can use *errorPrettyPrint()*.

[source, java]
----
var as = seq(c("aaa"), c('\n'), c("aaa"));

var result = as.parse("""
aaa
baa
""");
out.println(result.errorPrettyPrint());
----

----
aaa
>>baa
--------
Line: 1, Column: 0
expected "aaa"
----
