= Introduction

*JavaParsec* enables parsing in a pure functional way via https://wiki.haskell.org/index.php?title=Combinator_pattern[combinator pattern].
It is written in Java 21 and makes use of sealed classes, pattern matching and records. All operations are type-safe
and there are no casting or null exceptions.



=== Motivation

Creating a parser for new language or DSL is a big commitment.
The amount of work is sometimes prohibitive for starting small and
just experimenting with ideas. On the other hand generating full blown parser from
ANTLR makes the iteration loops longer plus you have to learn a new library.

Pure functional languages are attractive for write parsers, because of:

* *REPL and quick iteration loops* -  code consists of small or medium-sized
functions that are directly testable in eval loop.
You don't even have to write tests since you are already testing it in REPL.

* *composability without side effects* - because there is no mutable state
the work boils down to wiring big functions from smaller functions.
Once done - it is done, hardly ever the code needs runtime debugging,
which especially for complex parsers is  desired property.

* *delegating correctness checking to type checker* - the more checking is delegated
to types, the less runtime debugging, plus your IDE can more help you


*JavaParsec* brings this coding experience to Java land.
It is a toolkit of parser combinators - parser objects both primitive and composite
that match given pattern in a greedy manner. Every parser is composable
with another and together they form yet another composite parser.

There are various way that the library can be used, but it was designed primarily for
quick experimentation and fast debuging. The coding experience is very much like
scripting. This is why each parser is separated and complete
on its own and ready to use. You can test each part separately on whatever input you like.

For usage there a several recommended options:

* scratch files in IDE
* https://www.jbang.dev/[JBang] with VSCodium editing
* https://jupyter.org/[Jupyter] notebook with Java
* java 24 implicit class main functions


=== Quick Examples

For a real life examples refer to examples folder in repository.


**Parsing ISO Date**

[source, java]
----
public void main() {

    var year = times(digit(), 4).str()
            .map(Integer::valueOf);

    var month = times(digit(), 2).str()
            .map(Integer::valueOf)
            .failIf(i -> i < 1 || i > 12, "wrong month");

    var day = times(digit(), 2).str()
            .map(Integer::valueOf)
            .failIf(i -> i > 31, "wrong day");

    var date = seq(
            year,
            anyOf('-'),
            month,
            anyOf('-'),
            day
    ).map(t -> LocalDate.of(t.one(), t.three(), t.five()));


    println(date.parse("2024-03-23"));
}
----

**Parsing integer literal**

[source, java]
----
public void main(String[] args) {
   var zero = c("0").map(Integer::valueOf);

   var nonZero = seq(
    nonZeroDigit(),
    many(digit()).str()
   ).str().map(Integer::valueOf);

   var zeroNotFollowed = zero.dropRight(not(some(digit())));

   var integer = any(zeroNotFollowed, nonZero);

   assert integer.parse("0").ok() == 0;
   assert integer.parse("123").ok() == 123;
   assert !integer.parse("001").isOk();
}
----

=== License

This code is available under https://www.apache.org/licenses/LICENSE-2.0[Apache License Version 2.0]