= Usage tutorial

Writing simplified Markdown parser

=== Intro

In this section we will parse subset of Markdown
syntax with library constructs. To make this part shorter this
won't be the full Markdown sytax. Markdown handles content as
a list of blocks. It can be either a heading title, paragraph or a block quote.
They are separated by a blank line - a line that contains only whitespaces.

----
MarkdownDocument  ::=  Block*
Block             ::=  HeadingBlock
                   |  Paragraph
                   |  BlockQuote
                   |  BlankLine
----

Heading block starts with multiplicity of '#' contains alphanumeric characters and
is ended by a newline.

----
ATXHeading      ::=  "#"{1, 6} [Space] Text LineBreak
----

On the other hand paragraph allows single line breaks. It will allow for formatting text with common markdown
punctuation, like strong, italics and code.

----
Paragraph       ::=  (InlineContent (Space | LineBreak)*)+
----


Block quote consists of text lines prefixed by '>'

----
BlockQuote      ::=  (">" [Space] Text LineBreak)+
----

And finally the blank line.

----
BlankLine       ::=  (Space | Tab)* LineBreak
----

Inline content in this example appears only in paragraph. It is a couple of
variant either normal text or formatted.

----
InlineContent    ::=  InlineElement*
InlineElement    ::=  Text
                   |  Emphasis
                   |  Strong
                   |  InlineCode
                   |  Link

Emphasis ::= `"*" Text "*"
Strong = "**" Text "**"
InlineCode  = "`" Text "`"
Link   =  "[" Text "]" "(" Text ")"
----

=== Parsing inline elements

Text elements are plain characters without the puctuation of markdown. `noneOf` matches any of the characters that is not specified.
Then we can combine it with higher level parser combinator - `some`.
`some()` takes at least one or more occurences of given inner parser. Since
we fed it with single char parser we get list of chars. A convenience method `str()` will join them into string.

[source, java]
----
public void main(String[] args) {
    var textSingle = noneOf('*', '`', '[', ']', '(', ')', '>', '\n');

    var text = some(textSingle).str();

    var r1 = text.parse("this some text");

    out.println(r1.ok());

}
----

Combinators are greedy that they will take up input until it is valid. So in the
case of encountering markdown punctuation, `text` parser will stop there.

[source, java]
----
public void main(String[] args) {
    var textSingle = noneOf('*', '`', '[', ']', '(', ')', '>', '\n');

    var text = some(textSingle).str();

    var r1 = text.parse("this some *text*");

    if (r1 instanceof Ok(String s, Context ctx)) {
        assert r1.ok().equals("this some ");
        assert ctx.index == ctx.content.indexOf("*");

    } else {
        throw new ParseException("unexpected");
    }

}
----

`some()` succeeded because we have at least one character matching, but
the text got parsed up to the first occurence of '*'.

To make fast assertions inline we can use convenience methods on the parser itself.
Take a look at:

* link:apidocs/org/jparsec/Matcher.html#assertEquals(org.jparsec.containers.Context,T)[assertEquals]
* link:apidocs/org/jparsec/Matcher.html#assertFails(java.lang.String)[assertFails]
* link:apidocs/org/jparsec/Matcher.html#assertParses(java.lang.String)[assertParses]


[source, java]
----
public void main(String[] args) {
    var textSingle = noneOf('*', '`', '[', ']', '(', ')', '>', '\n');

    var text = some(textSingle).str();

    text.assertEquals(
        Context.of("this some *text*"), "this some ");

}
----

Before we introduce next rule it will be good to define conatiners for the results.
If you had a chance to meet _Algebraic Data Types_ then sealed interfaces and records are
the way to achieve this result.

[source, java]
----
sealed interface Inline {
    record Text(String value) implements Inline{};
    record Emphasis(String value) implements Inline{};
    record Strong(String value) implements Inline{};
    record Code(String value) implements Inline{};
    record Link(String text, String url) implements Inline{};
}
----

Here we will write emphasis parser. It is enclosed in '*' characters and inside there is
normal text. We can model one rule occuring after another with link:apidocs/org/jparsec/Api.html#seq(org.jparsec.Matcher,org.jparsec.Matcher,org.jparsec.Matcher)[seq()] combinator that takes
up to 7 rules. What is important that it is totally typesafe thanks to generics.

[source, java]
----

var emphasis = seq(c('*'), text, c('*'))
    .map(Ops::takeMiddle).map(Inline.Text::new);

out.println(emphasis.parse("*emphasis*").ok());
----

Result
----
Text[value=emphasis]
----

Quick assertion that formatted text will not pass.

[source, java]
----
emphasis.assertFails("*emphasis `code`*");
----
Text gets only parsed up to '`', but then we have to end the rule with '*' which is not matched.

The other rules are handled in similar fashion.

[source, java]
----
public void main(String[] args) {
    var textSingle = noneOf('*', '`', '[', ']', '(', ')', '>', '\n');
    var text = some(textSingle).str();

    var emphasis = seq(c('*'), text, c('*'))
        .map(Ops::takeMiddle).map(Inline.Emphasis::new);

    emphasis.assertFails("* emphasis `code`*");
    emphasis.assertEquals(Context.of("*text*"),  new Inline.Emphasis("text"));

    var strong = seq(c("**"), text, c("**"))
        .map(Ops::takeMiddle).map(Inline.Strong::new);

    strong.assertFails("** strong *nested* **");
    strong.assertEquals(Context.of("**strong**"), new Inline.Strong("strong"));

    var codeText = some(noneOf('`', '\n')).str();
    var code = seq(c('`'), codeText, c('`'))
        .map(Ops::takeMiddle).map(Inline.Code::new);
    code.assertEquals(Context.of("`code ()*[]`"), new Inline.Code("code ()*[]"));

    var link = seq(c('['), text, c(']'), c('('), text, c(')'))
        .map( tuple6 -> new Inline.Link(tuple6.two(), tuple6.five()));
    link.assertEquals(Context.of("[desc](https://link)"), new Inline.Link("desc", "https://link"));

    var inline = choice(link, strong, code, emphasis, text)
        .map(ch5 ->
            switch (ch5) {
                case One(Inline.Link l) -> (Inline) l;
                case Two(Inline.Strong s) -> (Inline) s;
                case Three(Inline.Code c) -> (Inline) c;
                case Four(Inline.Emphasis e) -> (Inline) e;
                case Five(String t) -> (Inline) new Inline.Text(t);
            }
        );

    var r2 = some(inline).parse("text with **strong** and `code`");
    out.println(r2.ok());

}
----

The result:

----
[Text[value=text with ], Strong[value=strong], Text[value= and ], Code[value=code]]
----

=== Parsing blocks

The most complex case is paragraph because it has to incorporate stylized text.
For headers and links we will just parse simple text.
link:apidocs/org/jparsec/Api.html#sepBy(org.jparsec.Matcher,org.jparsec.Matcher)[sepBy()] parser
will intercalate first parser with the second parser. The separator can be just anything, here
we will just use newline or multiplicity of spaces.

[source, java]
----
var paragraph = sepBy(inline, (c('\n').or(some(c(' ')))));
var r3 = paragraph.parse("""
        normal text   *emphasis text*
        **strong text**
        `code text`
        """);
assert r3.isOk();
----

Block quote is a possibly multiline text each line starting with '>'. Here we will join on newlines and
we will merge strings with space as separator.

[source, java]
----
 var blockQuote = sepBy(
    seq(c('>'), text)
        .map(Ops::takeSecond),
    c('\n')).map(list -> String.join(" ", list));

var r4 = blockQuote.parse("""
        first line
        second line
        """);
assert r4.ok().equals("first line second line");
----

We can separate whole blocks by a blank line.

[source, java]
----
var blankLine = seq(many(c(' ')), some(c('\n')));

var r5 = sepBy(paragraph, blankLine).parse("""
        paragraph 1

        paragraph 2
        """);
assert r5.ok().size() == 2;
----

Heading is a simple text prefixed by number of '#' s. We can use link:apidocs/org/jparsec/Api.html#times(org.jparsec.Matcher,int,int)[times()]
matcher which asserts that the number of inner rule's occurrences is exactly in the range.

[source, java]
----
var heading = seq(
        times(c('#'), 1, 6)
            .map(List::size),
        many(c(' ')),
        text
).map(p -> new Block.HeadingBlock(p.one(), p.three()));

heading.assertEquals(Context.of("## heading 2"), new Block.HeadingBlock(2, "heading 2"));
----

Quick note on mapping method. Sequences return link:apidocs/org/jparsec/containers/seq/Tuple3.html[tuple objects]
that are again up to 7. They are typesafe with the help of generics.


And now we are ready to combine everything together:

[source, java]
----
public void main(String[] args) {
    var textSingle = noneOf('*', '#', '`', '[', ']', '(', ')', '>', '\n');
    var text = some(textSingle).str();

    var emphasis = seq(c('*'), text, c('*'))
        .map(Ops::takeMiddle).map(Inline.Emphasis::new);

    emphasis.assertFails("* emphasis `code`*");
    emphasis.assertEquals(Context.of("*text*"),  new Inline.Emphasis("text"));

    var strong = seq(c("**"), text, c("**"))
        .map(Ops::takeMiddle).map(Inline.Strong::new);

    strong.assertFails("** strong *nested* **");
    strong.assertEquals(Context.of("**strong**"), new Inline.Strong("strong"));

    var codeText = some(noneOf('`', '\n')).str();
    var code = seq(c('`'), codeText, c('`'))
        .map(Ops::takeMiddle).map(Inline.Code::new);
    code.assertEquals(Context.of("`code ()*[]`"), new Inline.Code("code ()*[]"));

    var link = seq(c('['), text, c(']'), c('('), text, c(')'))
        .map( tuple6 -> new Inline.Link(tuple6.two(), tuple6.five()));
    link.assertEquals(Context.of("[desc](https://link)"), new Inline.Link("desc", "https://link"));

    var inline = choice(link, strong, code, emphasis, text)
        .map(ch5 ->
            switch (ch5) {
                case One(Inline.Link l) -> (Inline) l;
                case Two(Inline.Strong s) -> (Inline) s;
                case Three(Inline.Code c) -> (Inline) c;
                case Four(Inline.Emphasis e) -> (Inline) e;
                case Five(String t) -> (Inline) new Inline.Text(t);
            }
        );


    var paragraph = sepBy(inline, (c('\n').or(many(c(' ')))))
         .map(Block.Paragraph::new);
    var r3 = paragraph.parse("""
            normal text   *emphasis text*
            **strong text**
            `code text`
            """);
    assert r3.isOk();

    var blockQuote = sepBy(
        seq(c('>'), text)
            .map(Ops::takeSecond),
        c('\n')).map(list -> String.join(" ", list))
        .map(Block.BlockQoute::new);

    var r4 = blockQuote.parse("""
            first line
            second line
            """);
    assert r4.ok().equals(new Block.BlockQoute("first line second line"));

    var blankLine = seq(many(c(' ')), many(c('\n')));

    var r5 = sepBy(paragraph, blankLine).parse("""
            paragraph 1

            paragraph 2
            """);
    assert r5.ok().size() == 2;

    var heading = seq(
            times(c('#'), 1, 6)
                .map(List::size),
            many(c(' ')),
            text
    ).map(p -> new Block.Heading(p.one(), p.three()));

    heading.assertEquals(Context.of("## heading 2"), new Block.Heading(2, "heading 2"));

    var block = choice(blockQuote, paragraph, heading)
            .map(t3 -> switch(t3) {
                case One(Block.BlockQoute q) -> (Block) q;
                case Two(Block.Paragraph p) -> (Block) p;
                case Three(Block.Heading h) -> (Block) h;
            });

    var markdown = sepBy(block, blankLine);

    var test = """
            This is a **strong** paragraph.
            With `code`

            # Heading 1

            > Some interesting
            > quote
            """;

    out.println(markdown.parse(test).ok());
}
----

The result
----
[Paragraph[elements=[Text[value=This is a ], Strong[value=strong], Text[value=paragraph.], Text[value=With ], Code[value=code]]], Heading[nestLevel=1, text=Heading 1], BlockQoute[text= Some interesting  quote]]
----

Note that we are doing it in iterative way. We started with bottom-most rule
and built up to more complex ones. The experience was much like working in REPL.
This way you can speed up the process significantly.


